export const GRUPO_LIST_REQUEST = 'GRUPO_LIST_REQUEST'
export const GRUPO_LIST_SUCCESS = 'GRUPO_LIST_SUCCESS'
export const GRUPO_LIST_FAIL = 'GRUPO_LIST_FAIL'

export const GRUPO_DETAILS_REQUEST = 'GRUPO_DETAILS_REQUEST'
export const GRUPO_DETAILS_SUCCESS = 'GRUPO_DETAILS_SUCCESS'
export const GRUPO_DETAILS_FAIL = 'GRUPO_DETAILS_FAIL'