# Generated by Django 4.0.4 on 2022-05-19 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_grupo_image_alter_activity_image_alter_blog_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='grupo',
        ),
    ]
