# Generated by Django 4.0.4 on 2022-06-03 17:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_blogdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogDetails',
            new_name='BlogDetail',
        ),
    ]
