# Generated by Django 4.0.4 on 2022-06-03 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_blogdetails_blogdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.blog'),
        ),
    ]
