# Generated by Django 4.0.4 on 2022-06-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_blogdetail_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
