# Generated by Django 4.0.4 on 2022-06-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_blogdetail_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='numReviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
