# Generated by Django 4.0.4 on 2022-06-05 18:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0010_blog_numreviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogDetail',
            new_name='Bdetail',
        ),
    ]
