# Generated by Django 4.0.4 on 2022-06-05 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_blogdetail_bdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog',
        ),
    ]
