# Generated by Django 4.0.4 on 2022-06-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_bdetail_rating_alter_blog_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='rating',
        ),
    ]
