# Generated by Django 4.0.4 on 2022-06-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_forum_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='image',
        ),
    ]
