# Generated by Django 4.0.4 on 2022-06-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='images'),
        ),
    ]
