# Generated by Django 4.0.4 on 2022-06-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='grupo',
        ),
        migrations.AlterField(
            model_name='forum',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
