# Generated by Django 4.0.4 on 2022-07-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
