# Generated by Django 4.0.4 on 2022-11-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
