# Generated by Django 4.0.4 on 2022-11-02 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0033_recording_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image1', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('image5', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('image6', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('tech_file', models.FileField(blank=True, null=True, upload_to='')),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('spec1', models.CharField(blank=True, max_length=200, null=True)),
                ('spec2', models.CharField(blank=True, max_length=200, null=True)),
                ('spec3', models.CharField(blank=True, max_length=200, null=True)),
                ('spec4', models.CharField(blank=True, max_length=200, null=True)),
                ('spec5', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('numReviews', models.IntegerField(blank=True, default=0, null=True)),
                ('pricereg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('pricedis', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('countInStock', models.IntegerField(blank=True, default=0, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
