# Generated by Django 4.0.4 on 2022-11-02 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
