# Generated by Django 4.0.4 on 2022-11-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='licencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
