# Generated by Django 4.0.4 on 2022-11-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_recording_licencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
