# Generated by Django 4.0.4 on 2022-11-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_topic_comment_rtf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='comment',
        ),
    ]
